// Demo data shown when no session exists (unauthenticated / demo mode).
// Gives collaborators and new visitors a realistic view of the app.

export const DEMO_MESSAGES = [
  {
    id: 'demo-1',
    recipient_name: 'Eve Summers',
    recipient_email: 'eve@example.com',
    subject: 'Happy birthday, always',
    body: `Eve,\n\nIf you're reading this, I'm gone — but I didn't want your birthday to pass without a word from me. You were one of the brightest parts of my life, and I hope that wherever you are, there is light and people who love you.\n\nWith all my love,\nAlice`,
    delivery_type: 'recurring',
    recurring_month: 6,
    recurring_day: 15,
    recurring_years: 3,
    status: 'active',
    created_at: '2026-03-12T00:00:00Z',
    updated_at: '2026-03-12T00:00:00Z',
  },
  {
    id: 'demo-2',
    recipient_name: 'David Chen',
    recipient_email: 'david@example.com',
    subject: 'A note for you',
    body: `David,\n\nI've been meaning to write this for some time. There are things I never said to you in life that I want you to know. You were a better friend to me than I ever deserved, and I'm grateful for every one of those years.\n\nAlice`,
    delivery_type: 'one_time',
    recurring_month: null,
    recurring_day: null,
    recurring_years: null,
    status: 'draft',
    created_at: '2026-03-28T00:00:00Z',
    updated_at: '2026-03-29T00:00:00Z',
  },
  {
    id: 'demo-3',
    recipient_name: 'Frank Reyes',
    recipient_email: 'frank@example.com',
    subject: null,
    body: `Frank,\n\nThank you for everything. You know what I mean.\n\nAlice`,
    delivery_type: 'one_time',
    recurring_month: null,
    recurring_day: null,
    recurring_years: null,
    status: 'delivered',
    created_at: '2025-11-04T00:00:00Z',
    updated_at: '2025-11-04T00:00:00Z',
  },
  {
    id: 'demo-4',
    recipient_name: 'Grace Okafor',
    recipient_email: 'grace@example.com',
    subject: 'Just in case',
    body: `Grace,\n\nI changed my mind. Some things are better left unsaid.\n\nAlice`,
    delivery_type: 'one_time',
    recurring_month: null,
    recurring_day: null,
    recurring_years: null,
    status: 'cancelled',
    created_at: '2025-09-17T00:00:00Z',
    updated_at: '2025-09-17T00:00:00Z',
  },
]

export const DEMO_EXECUTORS = [
  {
    id: 'demo-ex-1',
    name: 'Carol Whitman',
    email: 'carol@example.com',
    is_backup: false,
    invite_sent_at: '2026-03-05T00:00:00Z',
    accepted_at: '2026-03-06T00:00:00Z',
  },
  {
    id: 'demo-ex-2',
    name: 'James Obi',
    email: 'james@example.com',
    is_backup: true,
    invite_sent_at: '2026-03-10T00:00:00Z',
    accepted_at: null,
  },
]
